### ISSUE TITLE
Unable to run 'npm install'

### ISSUE THREAD

**Issue by santumerino** [tweetback/tweetback#138]
Hello!

I'm trying to get this project running, but every time I run `npm install`, I run into an error and can't proceed with the next step.
What's really embarrasing is that [I got this to work in the past](https://www.santumerino.com/twitterarchive/), but I've since forgotten how to do it. I'm currently running Linux Mint (Ubuntu-based) if that's relevant.

Please find below the bit of the log showing the error (everything before this had no issues running):
```
2731 info run sharp@0.32.6 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
2732 info run sqlite3@5.1.7 install node_modules/sqlite3 prebuild-install -r napi || node-gyp rebuild
2733 info run sharp@0.32.6 install { code: 1, signal: null }
2734 info run sqlite3@5.1.7 install { code: 0, signal: null }
2735 timing build:run:install:node_modules/sqlite3 Completed in 325ms
2736 timing reify:rollback:createSparse Completed in 385ms
2737 timing reify:rollback:retireShallow Completed in 1ms
2738 timing command:install Completed in 43996ms
2739 verbose stack Error: command failed
2739 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
2739 verbose stack     at ChildProcess.emit (events.js:314:20)
2739 verbose stack     at maybeClose (internal/child_process.js:1022:16)
2739 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2740 verbose pkgid sharp@0.32.6
2741 verbose cwd /home/santumerino/Downloads/tweetback-main
2742 verbose Linux 5.15.0-119-generic
2743 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
2744 verbose node v12.22.9
2745 verbose npm  v8.5.1
2746 error code 1
2747 error path /home/santumerino/Downloads/tweetback-main/node_modules/sharp
2748 error command failed
2749 error command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
2750 error /home/santumerino/Downloads/tweetback-main/node_modules/tar-fs/index.js:6
2750 error const win32 = (global.Bare?.platform || process.platform) === 'win32'
2750 error                            ^
2750 error
2750 error SyntaxError: Unexpected token '.'
2750 error     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2750 error     at Module._compile (internal/modules/cjs/loader.js:963:27)
2750 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2750 error     at Module.load (internal/modules/cjs/loader.js:863:32)
2750 error     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2750 error     at Module.require (internal/modules/cjs/loader.js:887:19)
2750 error     at require (internal/modules/cjs/helpers.js:85:18)
2750 error     at Object.<anonymous> (/home/santumerino/Downloads/tweetback-main/node_modules/sharp/install/libvips.js:18:15)
2750 error     at Module._compile (internal/modules/cjs/loader.js:999:30)
2750 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2751 verbose exit 1
2752 timing npm Completed in 44314ms
2753 verbose unfinished npm timer reify 1726281206166
2754 verbose unfinished npm timer reify:build 1726281249438
2755 verbose unfinished npm timer build 1726281249439
2756 verbose unfinished npm timer build:deps 1726281249439
2757 verbose unfinished npm timer build:run:install 1726281249464
2758 verbose unfinished npm timer build:run:install:node_modules/sharp 1726281249464
2759 verbose code 1
```
If anyone has any ideas on how to fix this, I would be eternally thankful!

**Comment by cooljeanius** [comment]
according to #136 some dependencies need to be updated anyways, so maybe solving that will also solve this...
