### ISSUE TITLE
ERR_INVALID_URL errors during build

### ISSUE THREAD

**Issue by tbroyer** [tweetback/tweetback#20]
Running `npm run build` (after copying/modifying my `tweets.js` and running `npm run import`) generated this error:
```
TypeError: Cannot read properties of null (reading 'domain')
    at Index.getLinkUrls (/home/…/tweetback/src/twitter.js:67:31)
    at Index.getAllLinks (/home/…/tweetback/index.11ty.js:166:26)
    at Index.render (/home/…/tweetback/index.11ty.js:254:20)
    at async Template._render (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
    at async TemplateMap.populateContentDataInMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
    at async TemplateMap.cache (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
    at async TemplateWriter._createTemplateMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
    at async TemplateWriter.generateTemplates (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
    at async TemplateWriter.write (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:324:23)
    at async Eleventy.executeBuild (/home/…/tweetback/node_modules/@11ty/eleventy/src/Eleventy.js:1121:13)
```
followed by several errors like this one:
```
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at Index.getLinkUrls (/home/…/tweetback/src/twitter.js:62:19)
    at Index.getTopHosts (/home/…/tweetback/index.11ty.js:177:21)
    at Index.render (/home/…/tweetback/index.11ty.js:349:13)
    at async Template._render (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
    at async TemplateMap.populateContentDataInMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
    at async TemplateMap.cache (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
    at async TemplateWriter._createTemplateMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5) {
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
```

and that's probably what causes the final error:
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering 11ty.js template ./tweet-pages.11ty.js (via TemplateContentRenderError)
[11ty] 2. Cannot read properties of undefined (reading 'indexOf') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'indexOf')
[11ty]     at TweetToFile.renderFullText (/home/…/tweetback/src/twitter.js:149:25)
[11ty]     at async TweetToFile.renderTweet (/home/…/tweetback/src/twitter.js:242:30)
[11ty]     at async TweetToFile.renderTweetThread (/home/…/tweetback/src/twitter.js:300:6)
[11ty]     at async TweetToFile.render (/home/…/tweetback/tweet-pages.11ty.js:22:10)
[11ty]     at async Template._render (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
[11ty]     at async TemplateMap.populateContentDataInMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
[11ty]     at async TemplateMap.cache (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
[11ty]     at async TemplateWriter._createTemplateMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
[11ty]     at async TemplateWriter.generateTemplates (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
[11ty]     at async TemplateWriter.write (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:324:23)
```

Using
```shell-session
$ node --version
v18.12.1
$ npm --version
8.19.2
```

How to debug that? (running with `DEBUG=Eleventy*` doesn't give much more information, seems to be only noise)
Maybe find which tweet is "in error" and manually fix the tweets.js and re-run `npm run import`? But how to find those tweets?

**Comment by nhoizey** [comment]
It looks like it comes from https://github.com/tweetback/tweetback/blob/main/src/twitter.js#L62 :

```javascript
let urlObj = new URL(url.expanded_url);
```

The structure of one URL in the JSON is like this (from my own archive):

```json
{
  "entities": {
    "urls": [
      {
        "url": "https://t.co/FKCPo0MD8d",
        "expanded_url": "https://twitter.com/MacGeneration/status/1052955572058767360",
        "display_url": "twitter.com/MacGeneration/…",
        "indices": ["26","49"]
      }
    ]
  }
}
```

So I would look for a issue with one of your `entities.urls.expanded_url`.

You can get the list of all these URLs with this SQL query to run in the sqlite database:

```sql
SELECT DISTINCT id_str AS twwet_id, json_tree.value AS expanded_url
FROM tweets, json_tree(tweets.json, '$.entities')
WHERE json_tree.key='expanded_url'
AND json_tree.value IS NOT NULL;
```

You'll then have to find if some of these URL are wrong, maybe running a Node script to test them with `new URL()`.

**Comment by tbroyer** [comment]
OK so I simply added a `console.log(url)` next to the `console.log(e)` at https://github.com/tweetback/tweetback/blob/7a687c1e8d0ed085ec5b56c175b5403c1eac76a5/src/twitter.js#L70 and this is what it gives me; two kinds of errors.

One with punycode in the TLD, that parse-domain apparently doesn't handle:
```
{
  url: 'https://t.co/fhSMuJ5auY',
  expanded_url: 'http://xn--19-t1i2dwepdte.xn--q7ce6a/',
  display_url: 'ໂຄວິດ19.ລາວ',
  indices: [ '44', '67' ]
}
TypeError: Cannot read properties of null (reading 'domain')
```
the other because there's no expanded_url (here, a tweet from 2013):
```
{ url: 'http://t.co/zA66GCLKLg', indices: [ '111', '133' ] }
TypeError [ERR_INVALID_URL]: Invalid URL
[…]
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
```

**Comment by tbroyer** [comment]
The parse-domain error is apparently fixed in v3 (released 2 years ago) but the code project uses v2: https://github.com/peerigon/parse-domain/issues/82

**Comment by peterjanes** [comment]
For the undefined `url.expanded_url`s I've replaced the references in `src/twitter.js` with `url.expanded_url ?? url.url` and that at least lets the build finish.

**Comment by zachleat** [comment]
Shipped the fixes for this one! Thanks y’all!

**Comment by tbroyer** [comment]
I'm afraid there's still a stray `url.expanded_url` at line 151:
```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering 11ty.js template ./tweet-pages.11ty.js (via TemplateContentRenderError)
[11ty] 2. Cannot read properties of undefined (reading 'indexOf') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'indexOf')
[11ty]     at TweetToFile.renderFullText (/home/…/tweetback/src/twitter.js:151:25)
[11ty]     at async TweetToFile.renderTweet (/home/…/tweetback/src/twitter.js:244:30)
[11ty]     at async TweetToFile.renderTweetThread (/home/…/tweetback/src/twitter.js:302:6)
[11ty]     at async TweetToFile.render (/home/…/tweetback/tweet-pages.11ty.js:22:10)
[11ty]     at async Template._render (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
[11ty]     at async TemplateMap.populateContentDataInMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
[11ty]     at async TemplateMap.cache (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
[11ty]     at async TemplateWriter._createTemplateMap (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
[11ty]     at async TemplateWriter.generateTemplates (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
[11ty]     at async TemplateWriter.write (/home/…/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:324:23)
[11ty] Copied 1737 files / Wrote 0 files in 21.79 seconds (v2.0.0-canary.18)
```

**Comment by zachleat** [comment]
@tbroyer sorry about that! patched up now
