### ISSUE TITLE
Error trying to fetch-new-data (quite possibly on my end)

### ISSUE THREAD

**Issue by mirisuzanne** [tweetback/tweetback#32]
I set up a new app on https://developer.twitter.com/en, and set an env variable with the `TWITTER_BEARER_TOKEN`, but still get an error with `npm run fetch-new-data`. I am very much not an expert around APIs so it's entirely possible this is on my end - the docs don't provide a lot of detail here.

```
➜ npm run fetch-new-data

> tweetback@1.0.0 fetch-new-data
> node database/fetchFromApi.js

Fetching more tweets! undefined
{
  max_results: 100,
  expansions: 'in_reply_to_user_id,attachments.media_keys',
  'media.fields': 'width,height,alt_text,type,preview_image_url,url',
  'tweet.fields': 'attachments,author_id,conversation_id,created_at,entities,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,reply_settings,source,text,withheld'
}
TWITTER REQUEST to statuses/user_timeline (1500/15m) 1
ERROR Error: Bad response for https://api.twitter.com/2/users/by?usernames=terribleMia&user.fields=created_at,description (403): Forbidden
    at RemoteAssetCache.fetch (/Users/mia/Sites/tweetback/node_modules/@11ty/eleventy-fetch/src/RemoteAssetCache.js:73:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/Users/mia/Sites/tweetback/node_modules/p-queue/dist/index.js:163:29)
```

Any advice would be helpful, thanks!

**Comment by zachleat** [comment]
It looks like @janl had the same problem yesterday! https://chaos.social/@janl/109416081959020534

I don’t think we quite got to the bottom of it but I wonder if I messed something up. I should try to create a new app and see if I can repro

> just to start over here, I’m using a Bearer Token generated from the Twitter Developer Portal, see https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens

**Comment by mirisuzanne** [comment]
I'm fairly sure I have a Bearer Token (starts with all the 'AAAAA…' screaming). I suppose either it's not getting set right (I tried `.env` since it looks like `dotenv` is being used, and also tried using the netlify CLI), or there's some other missing piece of the puzzle?

**Comment by zachleat** [comment]
And none of these seem familiar? https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only#common-error-cases

It seems like you might have a bad token or there has been a misunderstanding about the type of token necessary here. Can you provide any more detail about whether the Bearer Token is app-only?

https://developer.twitter.com/en/docs/twitter-api/users/lookup/api-reference/get-users-by 

Note the section at the top 

Authentication methods supported by this endpoint	
[OAuth 1.0a](https://developer.twitter.com/en/docs/authentication/oauth-1-0a) is also available for this endpoint.
[OAuth 2.0 Authorization Code with PKCE](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code)
[OAuth 2.0 App-only](https://developer.twitter.com/en/docs/authentication/oauth-2-0/application-only)

This is what my portal looks like for my keys on https://developer.twitter.com/en/portal/projects-and-apps

![image](https://user-images.githubusercontent.com/39355/204368151-4ae360e2-59e7-4d80-aa9c-b2e6c3844746.png)

Note the v2 Access there (that’s important)

**Comment by nhoizey** [comment]
@mirisuzanne you mentioned Netlify CLI, so are you trying to run it on Netlify, or only locally? If on Netlify, you need to set the variable on Netlify too.

For me, running locally, it works with the key set in a `.env` file: `TWITTER_BEARER_TOKEN=…`

Here's the location of the key I took on Twitter (it indeed starts with a lot of `A`s):

![image](https://user-images.githubusercontent.com/78213/204375125-ec2cfff9-3d39-40ee-b863-fe393b7f4c44.png)

**Comment by mirisuzanne** [comment]
@nhoizey I set the environment variable in both places for testing (the CLI allows you to use netlify-defined tokens in local development). But I don't think this is the issue anyway, because @zachleat has found the issue!

I mean, I don't see the solution yet - but I absolutely have an app-only token, and it gives me the error listed at the bottom of that 'Common error cases' link, and my app only lists `v1.1 access`. So clearly I need to do some authentication steps, and get myself a better token. So I'll look into that. Thanks!

**Comment by mirisuzanne** [comment]
You should go ahead and close this out, since it seems clear the issue is on my end. At most it might be worth documenting that:

- you need a bearer token for v2 authenticated end point, not just any old screaming token
- in order to get that, you need the app to be part of a "project"
- you are only allowed a single project

(Actually getting this part set up is pretty low on my priorities, since there are only a few posts since my data download - and I'm not posting actively any more)
