### ISSUE TITLE
TypeError: parseDomain is not a function

### ISSUE THREAD

**Issue by stuartlangridge** [tweetback/tweetback#37]
When doing `npm run build`, I'm getting lots and lots of errors that look like:

```bash
TypeError: parseDomain is not a function
    at Index.getLinkUrls (/home/aquarius/Programs/Others/tweetback/src/twitter.js:63:25)
    at Index.getAllLinks (/home/aquarius/Programs/Others/tweetback/index.11ty.js:166:26)
    at Index.render (/home/aquarius/Programs/Others/tweetback/index.11ty.js:254:20)
    at async Template._render (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
    at async TemplateMap.populateContentDataInMap (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
    at async TemplateMap.cache (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
    at async TemplateWriter._createTemplateMap (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
    at async TemplateWriter.generateTemplates (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
    at async TemplateWriter.write (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/TemplateWriter.js:324:23)
    at async Eleventy.executeBuild (/home/aquarius/Programs/Others/tweetback/node_modules/@11ty/eleventy/src/Eleventy.js:1121:13)
```

did I break something locally? https://github.com/tweetback/tweetback/issues/20 seems to reference parseDomain not handling stuff, but that's closed, and I'm not sure it's relevant.

**Comment by nhoizey** [comment]
@stuartlangridge did you update your version of `tweetback`? @zachleat changed something yesterday that might fix your issue:
https://github.com/tweetback/tweetback/commit/24d083ebfac080cecfc96e02017ad79a9946e952

**Comment by nhoizey** [comment]
@stuartlangridge great! 👍
