### ISSUE TITLE
Building fails with 0 templates written and a null tweet object

### ISSUE THREAD

**Issue by MarcoZehe** [tweetback/tweetback#42]
When trying to build my site from my archive of [this account](https://twitter.com/marcozehe), I receive the following error, after the PassThrough copy has been completed.

```
[11ty] 1. Having trouble rendering 11ty.js template ./tweet-pages.11ty.js (via TemplateContentRenderError)
[11ty] 2. Cannot read properties of undefined (reading 'indexOf') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'indexOf')
[11ty]     at TweetToFile.renderFullText (/Users/marco/projects/twitter-marcozehe/src/twitter.js:150:25)
[11ty]     at async TweetToFile.renderTweet (/Users/marco/projects/twitter-marcozehe/src/twitter.js:243:30)
[11ty]     at async TweetToFile.renderTweetThread (/Users/marco/projects/twitter-marcozehe/src/twitter.js:301:6)
[11ty]     at async TweetToFile.render (/Users/marco/projects/twitter-marcozehe/tweet-pages.11ty.js:22:10)
[11ty]     at async Template._render (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateContent.js:473:22)
[11ty]     at async TemplateMap.populateContentDataInMap (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateMap.js:495:13)
[11ty]     at async TemplateMap.cache (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateMap.js:370:5)
[11ty]     at async TemplateWriter._createTemplateMap (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
[11ty]     at async TemplateWriter.generateTemplates (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
[11ty]     at async TemplateWriter.write (/Users/marco/projects/twitter-marcozehe/node_modules/@11ty/eleventy/src/TemplateWriter.js:324:23)
[11ty] Copied 8 files / Wrote 0 files in 483.35 seconds (v2.0.0-canary.18)
```

For a [second account](https://twitter.com/marcoinenglish), the import went flawlessly. The main difference is that for the former, the archive is significantly larger. I had to import 3 times, tweets.js, tweets-part1.js and tweets-part2.js, where I renamed the latter to tweets.js in turn so they could be imported. The tweet count went from 70991 from the first import to something in the 147000 range after the second and a final about 152000 tweets after the third, so it added, not overwrote, the imported data, so it seems. The archive of the second account is smaller, with only about 31000 tweets and only one tweets.js where I only had to run one import.

Any ideas?

**Comment by zachleat** [comment]
Looking at the stack trace I think this is a duplicate of #20, which was officially fixed 2 days ago but it looked like there was one more instance of the error that I missed that I patched up this morning—can you pull the latest version and try again?

Sorry about that!

**Comment by MarcoZehe** [comment]
Yes, the newest code fixed it, and the build has now written all over 152,000 files. And at an impressive build time, too. But this is an M1 Mac, so... Thanks for the fixes!
