### ISSUE TITLE
How to release without GitHub pages as a regular nginx host

### ISSUE THREAD

**Issue by ronilaukkarinen** [tweetback/tweetback#88]
Sorry if this is wrong place to ask, but I just moved the `_site` folder to public root and set up a host for it. Index.html works but search etc. won't. I'm getting these to log:

```log
2023/04/16 20:52:44 [error] 4021901#4021901: *5531 open() "/var/www/tweetback/_site/api/v1/instance" failed (2: No such file or directory), client: 88.115.137.236, server: twitter.rolle.design, request: "GET /api/v1/instance HTTP/2.0", host: "twitter.rolle.design"
2023/04/16 20:52:56 [error] 4021901#4021901: *5531 open() "/var/www/tweetback/_site/api/v1/instance" failed (2: No such file or directory), client: 88.115.137.236, server: twitter.rolle.design, request: "GET /api/v1/instance HTTP/2.0", host: "twitter.rolle.design"
```

and these to console:

```
to load resource: the server responded with a status of 404 ()
pagefind.js:1 Failed to load Pagefind metadata:

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
loadEntry @ pagefind.js:1
pagefind.js:1 

Uncaught (in promise) Error: Failed to load Pagefind metadata
    at PagefindInstance.loadEntry (pagefind.js:1:15005)
    at async PagefindInstance.init (pagefind.js:1:13737)
    at async Pagefind.init (pagefind.js:1:22615)
```

What should I do?
I'm not familiar with eleventy etc.

**Comment by halkeye** [comment]
I think you need to make _site as /var/www/tweetback/, not put _site into /var/www/tweetback/
